ASSET_HOST: localhost:3000
APPLICATION_HOST: localhost:3000
PORT: 3000
RACK_ENV: development
REDIS_URL: redis://127.0.0.1:6379
SECRET_KEY_BASE: development_secret
EXECJS_RUNTIME: Node
SMTP_ADDRESS: smtp.example.com
SMTP_DOMAIN: example.com
SMTP_PASSWORD: password
SMTP_USERNAME: username
WEB_CONCURRENCY: 1
AWS_REGION: us-east-1
AWS_ACCESS_KEY_ID: <put-your-key-here>
AWS_SECRET_ACCESS_KEY: <put-your-secret-here>
